function qs(sel){return document.querySelector(sel)}
function qsa(sel){return [...document.querySelectorAll(sel)]}
function getParam(name){return new URLSearchParams(location.search).get(name)}
function setupNav(){const btn=qs('.menu-toggle'); const nav=qs('.nav'); if(btn&&nav){btn.addEventListener('click',()=>nav.classList.toggle('open'))}}
function projectCard(p){return `<a class="card" href="project.html?id=${p.id}"><div class="thumb"><img src="${p.cover}" onerror="this.style.display='none';this.parentElement.innerHTML='${p.category}'"></div><div class="card-info"><h2 class="card-title">${p.title}</h2><div class="meta">${p.category} / ${p.year}</div></div></a>`}
function renderProjects(){const el=qs('#projectsGrid'); if(!el)return; let current='All'; const filters=qs('#filters'); const cats=['All','Commercial','Music Video','Documentary','Government']; filters.innerHTML=cats.map(c=>`<button class="${c==='All'?'active':''}" data-cat="${c}">${c}</button>`).join(''); function draw(){const items=current==='All'?PROJECTS:PROJECTS.filter(p=>p.category===current); el.innerHTML=items.map(projectCard).join('')} filters.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return; current=e.target.dataset.cat; qsa('#filters button').forEach(b=>b.classList.toggle('active',b.dataset.cat===current)); draw()}); draw()}
function renderProjectDetail(){const el=qs('#projectDetail'); if(!el)return; const p=PROJECTS.find(x=>x.id===getParam('id'))||PROJECTS[0]; document.title=`${p.title} — EXEET`; el.innerHTML=`<a class="back" href="projects.html">← BACK TO PROJECTS</a><h1 class="page-title">${p.title}</h1><div class="detail"><div><div class="video"><iframe src="${p.videoUrl}" allowfullscreen></iframe></div></div><div><div class="meta">${p.category} / ${p.year}</div><p class="sub">${p.description}</p><ul class="credits">${p.credits.map(c=>`<li>${c}</li>`).join('')}</ul></div></div>`}
function renderTeam(){const el=qs('#teamGrid'); if(!el)return; el.innerHTML=TEAM.map(m=>`<a class="card" href="member.html?id=${m.id}"><div class="thumb team-photo"><img src="${m.photo}" onerror="this.style.display='none';this.parentElement.innerHTML='${m.role}'"></div><div class="card-info"><h2 class="card-title">${m.name}</h2><div class="meta">${m.role}</div></div></a>`).join('')}
function renderMember(){const el=qs('#memberDetail'); if(!el)return; const m=TEAM.find(x=>x.id===getParam('id'))||TEAM[0]; document.title=`${m.name} — EXEET`; el.innerHTML=`<a class="back" href="team.html">← BACK TO TEAM</a><h1 class="page-title">${m.name}</h1><div class="detail"><div class="thumb team-photo"><img src="${m.photo}" onerror="this.style.display='none';this.parentElement.innerHTML='${m.role}'"></div><div><div class="meta">${m.role}</div><p class="sub">${m.bio}</p><div class="member-tags">${m.works.map(w=>`<span>${w}</span>`).join('')}</div></div></div>`}
function renderShowreel(){const el=qs('#showreelVideo'); if(!el)return; el.innerHTML=`<iframe src="${SITE.showreelUrl}" allowfullscreen></iframe>`}
function renderContact(){const el=qs('#contactContent'); if(!el)return; el.innerHTML=`<p class="sub">${SITE.contactText}</p><div class="contact-box"><a class="contact-item" href="mailto:${SITE.email}">EMAIL<br><br>${SITE.email}</a><div class="contact-item">LINE ID<br><br>${SITE.lineId}</div><a class="contact-item" href="${SITE.instagramUrl}" target="_blank">INSTAGRAM<br><br>OPEN</a><a class="contact-item" href="${SITE.youtubeUrl}" target="_blank">YOUTUBE<br><br>OPEN</a></div>`}
setupNav(); renderProjects(); renderProjectDetail(); renderTeam(); renderMember(); renderShowreel(); renderContact();
